<a href="https://colab.research.google.com/github/sahilji23/sahilji23/blob/main/creditcard_fraud.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
data=pd.read_csv("creditcard.csv")
data

Time        V1        V2        V3        V4        V5        V6  \
0         0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1         0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2         1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3         1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4         2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   
...     ...       ...       ...       ...       ...       ...       ...   
7968  10980  1.284388 -0.013181  0.646174  0.198985 -0.568675 -0.526121   
7969  10981  1.190428 -0.122329  0.954945  0.267101 -0.971026 -0.652279   
7970  10981 -0.725175  0.298202  1.824761 -2.587170  0.283605 -0.016617   
7971  10981  1.226153 -0.129645  0.735197  0.142752 -0.703245 -0.349641   
7972  10981  1.145381 -0.059349  0.968088  0.267891 -0.822582 -0.597727   

            V7        V8        V9  ...       V21       V22       V23  \
0     0.239599  0.098698  0.363787  ... -0.018307  0.277838 -0.110474   
1    -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288   
2     0.791461  0.247676 -1.514654  ...  0.247998  0.771679  0.909412   
3     0.237609  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321   
4     0.592941 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458   
...        ...       ...       ...  ...       ...       ...       ...   
7968 -0.448235 -0.167709  1.773223  ... -0.101868 -0.030298 -0.081412   
7969 -0.612992 -0.003909  1.633117  ... -0.015001  0.127027  0.012079   
7970  0.153659  0.045084 -0.197611  ... -0.017097 -0.070535 -0.442861   
7971 -0.612641  0.020507  1.648986  ... -0.047936  0.040196 -0.057391   
7972 -0.450197 -0.119747  1.338188  ...       NaN       NaN       NaN   

           V24       V25       V26       V27       V28  Amount  Class  
0     0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62    0.0  
1    -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69    0.0  
2    -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66    0.0  
3    -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50    0.0  
4     0.141267 -0.206010  0.502292  0.219422  0.215153   69.99    0.0  
...        ...       ...       ...       ...       ...     ...    ...  
7968 -0.123281  0.278808  1.064001 -0.090181  0.000481   15.95    0.0  
7969  0.534409  0.112179  1.004483 -0.100188 -0.004774   14.95    0.0  
7970 -0.895837  0.624743 -0.510601 -0.031142  0.025564   12.95    0.0  
7971 -0.012386  0.187685  1.037786 -0.100081 -0.009869   15.95    0.0  
7972       NaN       NaN       NaN       NaN       NaN     NaN    NaN  

[7973 rows x 31 columns]

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(data, *['Time'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(data, *['V1'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(data, *['V2'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(data, *['V3'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(data, *['Time'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(data, *['V1'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(data, *['V2'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(data, *['V3'], **{})
chart

import numpy as np
from google.colab import autoviz

def scatter_plots(df, colname_pairs, figscale=1, alpha=.8):
  from matplotlib import pyplot as plt
  plt.figure(figsize=(len(colname_pairs) * 6 * figscale, 6 * figscale))
  for plot_i, (x_colname, y_colname) in enumerate(colname_pairs, start=1):
    ax = plt.subplot(1, len(colname_pairs), plot_i)
    df.plot(kind='scatter', x=x_colname, y=y_colname, s=(32 * figscale), alpha=alpha, ax=ax)
    ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = scatter_plots(data, *[[['Time', 'V1'], ['V1', 'V2'], ['V2', 'V3'], ['V3', 'V4']]], **{})
chart

import numpy as np
from google.colab import autoviz

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (10 * figscale, 5.2 * figscale)
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(data, *['Time', 'V1', None], **{})
chart

import numpy as np
from google.colab import autoviz

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (10 * figscale, 5.2 * figscale)
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(data, *['Time', 'V2', None], **{})
chart

import numpy as np
from google.colab import autoviz

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (10 * figscale, 5.2 * figscale)
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(data, *['Time', 'V3', None], **{})
chart

import numpy as np
from google.colab import autoviz

def time_series_multiline(df, timelike_colname, value_colname, series_colname, figscale=1, mpl_palette_name='Dark2'):
  from matplotlib import pyplot as plt
  import seaborn as sns
  figsize = (10 * figscale, 5.2 * figscale)
  palette = list(sns.palettes.mpl_palette(mpl_palette_name))
  def _plot_series(series, series_name, series_index=0):
    if value_colname == 'count()':
      counted = (series[timelike_colname]
                 .value_counts()
                 .reset_index(name='counts')
                 .rename({'index': timelike_colname}, axis=1)
                 .sort_values(timelike_colname, ascending=True))
      xs = counted[timelike_colname]
      ys = counted['counts']
    else:
      xs = series[timelike_colname]
      ys = series[value_colname]
    plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

  fig, ax = plt.subplots(figsize=figsize, layout='constrained')
  df = df.sort_values(timelike_colname, ascending=True)
  if series_colname:
    for i, (series_name, series) in enumerate(df.groupby(series_colname)):
      _plot_series(series, series_name, i)
    fig.legend(title=series_colname, bbox_to_anchor=(1, 1), loc='upper left')
  else:
    _plot_series(df, '')
  sns.despine(fig=fig, ax=ax)
  plt.xlabel(timelike_colname)
  plt.ylabel(value_colname)
  return autoviz.MplChart.from_current_mpl_state()

chart = time_series_multiline(data, *['Time', 'V4', None], **{})
chart

In [ ]:
data=data.dropna()

In [ ]:
data.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [ ]:
fraud_trans=data[data["Class"]==1]
valid_trans=data[data["Class"]==0]
outlier_frac=len(fraud_trans)/len(valid_trans)
print(outlier_frac)

0.0031458411979363283


In [ ]:
print("fraud cases:{}".format(len(data[data["Class"]==1])))
print("valid cases:{}".format(len(data[data["Class"]==0])))


fraud cases:25
valid cases:7947


In [ ]:
data.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [ ]:
fraud_trans.Amount.describe()

count      25.000000
mean      106.308400
std       372.676883
min         0.000000
25%         1.000000
50%         1.000000
75%         1.000000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
valid_trans.Amount.describe()

count    7947.000000
mean       65.284891
std       194.126547
min         0.000000
25%         4.795000
50%        15.950000
75%        54.990000
max      7712.430000
Name: Amount, dtype: float64

In [ ]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values
best_result=[]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25,random_state=0)


###DecisionTreeClassifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model1=DecisionTreeClassifier(random_state=0)
model1.fit(x_train,y_train)

DecisionTreeClassifier(random_state=0)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred=model1.predict(x_test)
print(confusion_matrix(y_test,y_pred))
ans=accuracy_score(y_test,y_pred)
best_result.append(ans)
ans

[[1984    1]
 [   2    6]]


0.9984947315604616

### K-NN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model2=KNeighborsClassifier()
model2.fit(x_train,y_train)

KNeighborsClassifier()

##Confusion matrix of knn

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred=model2.predict(x_test)
print(confusion_matrix(y_test,y_pred))
ans=accuracy_score(y_test,y_pred)
best_result.append(ans)
ans

[[1985    0]
 [   7    1]]


0.9964877069744105

##kernel_svm

In [ ]:
from sklearn.svm import SVC
model3=SVC(random_state=0)
model3.fit(x_train,y_train)


SVC(random_state=0)

##confusion matrix of kernel_svm

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred=model3.predict(x_test)
print(confusion_matrix(y_test,y_pred))
ans=accuracy_score(y_test,y_pred)
best_result.append(ans)
ans

[[1985    0]
 [   8    0]]


0.9959859508278976

##Logistic_regression

In [ ]:
from sklearn.linear_model import LogisticRegression
model4=LogisticRegression(random_state=0)
model4.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

##confusion matrix of logistic_regression

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred=model4.predict(x_test)
print(confusion_matrix(y_test,y_pred))
ans=accuracy_score(y_test,y_pred)
best_result.append(ans)
ans

[[1985    0]
 [   3    5]]


0.9984947315604616

In [ ]:
best_result

[0.9984947315604616,
 0.9964877069744105,
 0.9959859508278976,
 0.9984947315604616]

## naive_bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
model5=GaussianNB()
model5.fit(x_train,y_train)

GaussianNB()

## confusion matrix of naive bayes

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred=model5.predict(x_test)
print(confusion_matrix(y_test,y_pred))
ans=accuracy_score(y_test,y_pred)
best_result.append(ans)
ans

[[1983    2]
 [   2    6]]


0.9979929754139488

## Random Forest Classification

In [ ]:
from sklearn.naive_bayes import GaussianNB
model6=GaussianNB()
model6.fit(x_train,y_train)

GaussianNB()

## confusion matrix of GaussianNB

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred=model6.predict(x_test)
print(confusion_matrix(y_test,y_pred))
ans=accuracy_score(y_test,y_pred)
best_result.append(ans)
ans

[[1983    2]
 [   2    6]]


0.9979929754139488

##Support vector machine

In [ ]:
from sklearn.svm import SVC
model7=SVC(kernel="linear",random_state=0)
model7.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

## confusion matrix of SVC

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
y_pred=model7.predict(x_test)
print(confusion_matrix(y_test,y_pred))
ans=accuracy_score(y_test,y_pred)
best_result.append(ans)
ans

[[1984    1]
 [   3    5]]


0.9979929754139488

In [ ]:
best_result

[0.9984947315604616,
 0.9964877069744105,
 0.9959859508278976,
 0.9984947315604616,
 0.9979929754139488,
 0.9979929754139488,
 0.9979929754139488]

### got best result through decisiontreeclassifier and logisitic regression